# Generated by Django 5.2.13 on 2026-06-09 05:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0007_add_canvas_course_id"),
        ("rag", "0002_coursematerialchunk_coursematerial_error_message_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CanvasProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("canvas_user_id", models.CharField(max_length=64, unique=True)),
                ("access_token", models.CharField(blank=True, max_length=255)),
                ("refresh_token", models.CharField(blank=True, max_length=255)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canvas_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "canvas_canvasprofile",
            },
        ),
        migrations.CreateModel(
            name="CanvasFileSync",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("canvas_file_id", models.CharField(max_length=64)),
                ("display_name", models.CharField(max_length=255)),
                ("filename", models.CharField(max_length=255)),
                ("size", models.PositiveBigIntegerField()),
                ("checksum", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canvas_file_syncs",
                        to="courses.course",
                    ),
                ),
                (
                    "material",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="canvas_sync",
                        to="rag.coursematerial",
                    ),
                ),
            ],
            options={
                "db_table": "canvas_canvasfilesync",
                "unique_together": {("course", "canvas_file_id")},
            },
        ),
    ]
