# Generated by Django 5.2.7 on 2025-12-14 19:45

from django.db import migrations
import uuid


def assign_homeworks_to_default_course(apps, schema_editor):
    """Create a default course and assign all existing homeworks to it."""
    Course = apps.get_model("courses", "Course")
    CourseHomework = apps.get_model("courses", "CourseHomework")
    Homework = apps.get_model("homeworks", "Homework")

    # Check if there are any homeworks to migrate
    if not Homework.objects.exists():
        return

    # Create the course for existing homeworks with specific ID
    course_id = uuid.UUID("6be09b3d-117d-4e65-acc5-bef0ac94311e")
    default_course = Course.objects.create(
        id=course_id,
        name="STAT302-Furfaro-First",
        code="STAT302-Furfaro-First",
        description="First instance of STAT302 course taught by Furfaro",
        is_active=True,
    )

    # Assign all existing homeworks to the course
    homeworks = Homework.objects.all()
    for homework in homeworks:
        CourseHomework.objects.create(
            id=uuid.uuid4(),
            course=default_course,
            homework=homework,
        )


def reverse_assignment(apps, schema_editor):
    """Remove all homework assignments from the course and delete it."""
    Course = apps.get_model("courses", "Course")
    CourseHomework = apps.get_model("courses", "CourseHomework")

    # Find the course by ID
    course_id = uuid.UUID("6be09b3d-117d-4e65-acc5-bef0ac94311e")
    try:
        default_course = Course.objects.get(id=course_id)
        # Delete all homework assignments for this course
        CourseHomework.objects.filter(course=default_course).delete()
        # Delete the course
        default_course.delete()
    except Course.DoesNotExist:
        # If the course doesn't exist, nothing to reverse
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("homeworks", "0001_initial"),  # Add dependency on homeworks app
    ]

    operations = [
        migrations.RunPython(
            assign_homeworks_to_default_course,
            reverse_assignment,
        ),
    ]
