# Generated by Django 5.2.7 on 2025-12-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_assign_existing_homeworks_to_default_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=256),
        ),
    ]
