# Generated by Django 5.2.7 on 2025-12-14 19:54

from django.db import migrations
import uuid


def add_teachers_and_students_to_course(apps, schema_editor):
    """Add all existing teachers and students to the STAT302-Furfaro-First course."""
    Course = apps.get_model("courses", "Course")
    CourseTeacher = apps.get_model("courses", "CourseTeacher")
    CourseEnrollment = apps.get_model("courses", "CourseEnrollment")
    Teacher = apps.get_model("accounts", "Teacher")
    Student = apps.get_model("accounts", "Student")

    # Get the course by ID
    course_id = uuid.UUID("6be09b3d-117d-4e65-acc5-bef0ac94311e")
    try:
        course = Course.objects.get(id=course_id)
    except Course.DoesNotExist:
        # If course doesn't exist, nothing to do
        return

    # Add all teachers to the course
    teachers = Teacher.objects.all()
    for index, teacher in enumerate(teachers):
        # Make the first teacher the owner, rest are co-teachers
        role = "owner" if index == 0 else "co_teacher"
        CourseTeacher.objects.create(
            id=uuid.uuid4(),
            course=course,
            teacher=teacher,
            role=role,
        )

    # Enroll all students in the course
    students = Student.objects.all()
    for student in students:
        CourseEnrollment.objects.create(
            id=uuid.uuid4(),
            course=course,
            student=student,
            is_active=True,
        )


def reverse_teachers_and_students(apps, schema_editor):
    """Remove all teachers and students from the course."""
    Course = apps.get_model("courses", "Course")
    CourseTeacher = apps.get_model("courses", "CourseTeacher")
    CourseEnrollment = apps.get_model("courses", "CourseEnrollment")

    # Get the course by ID
    course_id = uuid.UUID("6be09b3d-117d-4e65-acc5-bef0ac94311e")
    try:
        course = Course.objects.get(id=course_id)
        # Delete all teacher relationships for this course
        CourseTeacher.objects.filter(course=course).delete()
        # Delete all student enrollments for this course
        CourseEnrollment.objects.filter(course=course).delete()
    except Course.DoesNotExist:
        # If the course doesn't exist, nothing to reverse
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_alter_course_code_alter_course_name"),
        ("accounts", "0001_initial"),  # Add dependency on accounts app
    ]

    operations = [
        migrations.RunPython(
            add_teachers_and_students_to_course,
            reverse_teachers_and_students,
        ),
    ]
