# Generated by Django 5.2.7 on 2026-01-02 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_add_teachers_and_students_to_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="homeworks",
        ),
        migrations.DeleteModel(
            name="CourseHomework",
        ),
    ]
