# Generated by Codex on 2026-05-31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0003_teacherassistant"),
        ("courses", "0006_courseteacherassistant_course_teacher_assistants"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(default="application/pdf", max_length=100),
                ),
                ("size", models.PositiveBigIntegerField()),
                ("checksum", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="courses.course",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_course_materials",
                        to="accounts.teacher",
                    ),
                ),
            ],
            options={
                "db_table": "rag_course_material",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseMaterialBlob",
            fields=[
                (
                    "material",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="blob",
                        serialize=False,
                        to="rag.coursematerial",
                    ),
                ),
                ("data", models.BinaryField()),
            ],
            options={
                "db_table": "rag_course_material_blob",
            },
        ),
        migrations.AddIndex(
            model_name="coursematerial",
            index=models.Index(
                fields=["course", "-created_at"],
                name="rag_course__course__d2dc40_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coursematerial",
            index=models.Index(
                fields=["checksum"],
                name="rag_course__checksu_5906e1_idx",
            ),
        ),
    ]
