# Generated by Django 5.2.13 on 2026-05-31 21:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_teacherassistant"),
        ("courses", "0006_courseteacherassistant_course_teacher_assistants"),
        ("rag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseMaterialChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("page_group", "Page Group"), ("chunk", "Chunk")],
                        max_length=10,
                    ),
                ),
                ("chunk_index", models.IntegerField()),
                ("page_group_index", models.IntegerField(blank=True, null=True)),
                ("content", models.TextField()),
                ("page_start", models.IntegerField()),
                ("page_end", models.IntegerField()),
                ("embedding", models.BinaryField(blank=True, null=True)),
                ("token_count", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "rag_course_material_chunk",
                "ordering": ["material", "level", "chunk_index"],
            },
        ),
        migrations.AddField(
            model_name="coursematerial",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="coursematerial",
            name="pages",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coursematerial",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="coursematerial",
            index=models.Index(
                fields=["processing_status"], name="rag_course__process_8d3233_idx"
            ),
        ),
        migrations.AddField(
            model_name="coursematerialchunk",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="rag.coursematerial",
            ),
        ),
        migrations.AddIndex(
            model_name="coursematerialchunk",
            index=models.Index(
                fields=["material", "level"], name="rag_course__materia_3beddb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coursematerialchunk",
            unique_together={("material", "level", "chunk_index")},
        ),
    ]
