# Generated by Django 5.2.7 on 2026-03-30 02:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_email_verified_emailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssistant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assistant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_teacher_assistant',
            },
        ),
    ]
