# Generated by Django 5.2.13 on 2026-06-06 18:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacherassistant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canvas_user_id', models.CharField(max_length=64, unique=True)),
                ('access_token', models.CharField(blank=True, max_length=255)),
                ('refresh_token', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_canvas_profile',
            },
        ),
    ]
