# Generated by Django 5.2.13 on 2026-06-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_add_canvas_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="canvasprofile",
            name="token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
