# Generated by Django 5.2.13 on 2026-06-09 05:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_add_canvas_token_expiry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CanvasProfile",
        ),
    ]
