# Generated by Django 5.2.5 on 2025-09-29 03:12

from django.db import migrations


def update_model_names_for_openrouter(apps, schema_editor):
    """
    Update existing model names to use OpenRouter format (provider/model).

    Since all existing models are OpenAI models, this migration adds the
    'openai/' prefix to any model name that doesn't already have a provider prefix.
    """
    LLMConfig = apps.get_model("llm", "LLMConfig")

    # Update existing configurations
    for config in LLMConfig.objects.all():
        old_model_name = config.model_name

        # If model name doesn't have a provider prefix (no '/'), add 'openai/' prefix
        if "/" not in old_model_name:
            new_model_name = f"openai/{old_model_name}"
            config.model_name = new_model_name
            config.save()
            print(f"Added OpenAI prefix: {old_model_name} -> {new_model_name}")
        else:
            # Model name already has provider prefix, leave it as is
            print(f"Model name already has provider prefix: {old_model_name}")


def reverse_model_names_for_openrouter(apps, schema_editor):
    """
    Reverse the model name changes (remove openai/ prefixes).

    This is the reverse operation for rolling back the migration.
    """
    LLMConfig = apps.get_model("llm", "LLMConfig")

    # Update configurations by removing OpenAI prefix
    for config in LLMConfig.objects.all():
        model_name = config.model_name

        # Remove openai/ prefix if present
        if model_name.startswith("openai/"):
            new_model_name = model_name.replace("openai/", "", 1)
            config.model_name = new_model_name
            config.save()
            print(f"Removed OpenAI prefix: {model_name} -> {new_model_name}")


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0002_rename_max_tokens_to_max_completion_tokens"),
    ]

    operations = [
        migrations.RunPython(
            update_model_names_for_openrouter,
            reverse_model_names_for_openrouter,
        ),
    ]
