# Generated by Django 5.2.7 on 2026-03-30 14:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


def migrate_existing_configs_to_all_courses(apps, schema_editor):
    """Migrate existing LLM configs to all courses."""
    LLMConfig = apps.get_model("llm", "LLMConfig")
    Course = apps.get_model("courses", "Course")
    GlobalLLMDefault = apps.get_model("llm", "GlobalLLMDefault")

    existing_configs = LLMConfig.objects.filter(course__isnull=True, is_active=True)

    if not existing_configs.exists():
        return

    courses = Course.objects.filter(is_active=True)
    if not courses.exists():
        return

    for config in existing_configs:
        GlobalLLMDefault.objects.create(
            name=config.name,
            model_name=config.model_name,
            api_key=config.api_key,
            base_prompt=config.base_prompt,
            temperature=config.temperature,
            max_completion_tokens=config.max_completion_tokens,
            is_active=config.is_active,
        )

        for course in courses:
            LLMConfig.objects.create(
                course=course,
                name=config.name,
                model_name=config.model_name,
                api_key=config.api_key,
                base_prompt=config.base_prompt,
                temperature=config.temperature,
                max_completion_tokens=config.max_completion_tokens,
                is_default=config.is_default,
                is_active=config.is_active,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_courseteacherassistant_course_teacher_assistants"),
        ("llm", "0003_update_model_names_for_openrouter"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalLLMDefault",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "model_name",
                    models.CharField(
                        help_text="LLM model to use (e.g., 'gpt-4', 'gpt-3.5-turbo')",
                        max_length=100,
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        help_text="API key for LLM service", max_length=255
                    ),
                ),
                (
                    "base_prompt",
                    models.TextField(help_text="Base prompt template for AI tutor"),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(2.0),
                        ],
                    ),
                ),
                ("max_completion_tokens", models.PositiveIntegerField(default=1000)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "llm_global_default",
            },
        ),
        migrations.AddField(
            model_name="llmconfig",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_configs",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="llmconfig",
            unique_together={("course", "name")},
        ),
        migrations.RunPython(
            migrate_existing_configs_to_all_courses,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
