# Generated by Django 5.2.13 on 2026-06-01 02:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0006_courseteacherassistant_course_teacher_assistants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_chat",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(1)]
                    ),
                ),
                ("message_type", models.CharField(max_length=50)),
                (
                    "tool_call_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tool_call_arguments", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chat",
                    ),
                ),
            ],
            options={
                "db_table": "chat_chat_message",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessageContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_title", models.CharField(max_length=255)),
                ("page_start", models.IntegerField()),
                ("page_end", models.IntegerField()),
                (
                    "content",
                    models.TextField(help_text="The chunk text used as context"),
                ),
                (
                    "score",
                    models.FloatField(
                        help_text="Cosine similarity score (lower = closer)"
                    ),
                ),
                (
                    "query",
                    models.TextField(
                        help_text="The search query that triggered this retrieval"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contexts",
                        to="chat.chatmessage",
                    ),
                ),
            ],
            options={
                "db_table": "chat_chat_message_context",
                "ordering": ["score"],
            },
        ),
    ]
