# Generated by Django 5.2.7 on 2026-01-08 03:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasteEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pasted_content",
                    models.TextField(help_text="Full content that was pasted"),
                ),
                (
                    "word_count",
                    models.IntegerField(help_text="Number of words in pasted content"),
                ),
                (
                    "content_length",
                    models.IntegerField(help_text="Character length of pasted content"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "last_message_before_paste",
                    models.ForeignKey(
                        blank=True,
                        help_text="Last message sent before this paste event occurred",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paste_events_after",
                        to="conversations.message",
                    ),
                ),
            ],
            options={
                "db_table": "conversations_paste_event",
                "ordering": ["-timestamp"],
            },
        ),
    ]
