# Generated by Django 5.2.7 on 2026-01-16 07:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0002_pasteevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="RapidTextGrowthEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "added_text",
                    models.TextField(
                        help_text="Text that was added during the 100ms window"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "last_message_before_event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Last message sent before this rapid text growth event occurred",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rapid_text_growth_events_after",
                        to="conversations.message",
                    ),
                ),
            ],
            options={
                "db_table": "conversations_rapid_text_growth_event",
                "ordering": ["-timestamp"],
            },
        ),
    ]
