# Generated by Django 5.2.13 on 2026-05-03 20:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0004_sectionanswer"),
        ("homeworks", "0008_homeworkprogresswidget"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeworkProgressWidgetResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pre_value",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Slider value (0-10) for pre-condition response",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "post_value",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Slider value (0-10) for post-condition response",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "pre_submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when pre-condition was answered",
                        null=True,
                    ),
                ),
                (
                    "post_submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when post-condition was answered",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widget_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="homeworks.homeworkprogresswidget",
                    ),
                ),
            ],
            options={
                "db_table": "conversations_progress_widget_response",
                "ordering": ["-pre_submitted_at"],
                "unique_together": {("user", "widget")},
            },
        ),
    ]
