# Generated by Django 5.2.13 on 2026-05-03 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0005_homeworkprogresswidgetresponse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeworkprogresswidgetresponse",
            name="post_value",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Slider value (0-10) for post-condition response",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="homeworkprogresswidgetresponse",
            name="pre_value",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Slider value (0-10) for pre-condition response",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
