# Generated by Django 5.2.13 on 2026-05-23 00:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_alter_homeworkprogresswidgetresponse_post_value_and_more'),
        ('homeworks', '0008_homeworkprogresswidget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('feedback_type', models.CharField(choices=[('general', 'General'), ('needs_revision', 'Needs revision'), ('good_work', 'Good work'), ('clarify_reasoning', 'Clarify reasoning')], default='general', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_feedback', to='conversations.conversation')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_feedback', to='homeworks.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedback', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_feedback', to='conversations.submission')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversations_teacher_feedback',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('conversation__isnull', False)), fields=('teacher', 'conversation'), name='uniq_teacher_feedback_per_conversation')],
            },
        ),
    ]
