# Generated by Django 5.2.7 on 2026-01-02 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_remove_course_homeworks_delete_coursehomework"),
        ("homeworks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homeworks",
                to="courses.course",
            ),
        ),
    ]
