# Generated by Django 5.2.7 on 2026-03-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homeworks", "0004_alter_homework_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Automatically hide from students after this date. Leave blank to never auto-hide.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="is_hidden",
            field=models.BooleanField(
                default=False, help_text="Immediately hide this homework from students."
            ),
        ),
    ]
