# Generated by Django 5.2.7 on 2026-04-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homeworks", "0004_alter_homework_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("conversation", "Conversation (Interactive)"),
                    ("non_interactive", "Non-Interactive Question"),
                ],
                default="conversation",
                max_length=50,
            ),
        ),
    ]
