# Generated by Django 5.2.13 on 2026-04-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homeworks", "0005_section_section_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Automatically hide from students after this date. Leave blank to never auto-hide.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="homework_type",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("hidden", "Hidden"),
                ],
                default="published",
                help_text="Display label only. is_hidden is the access control source of truth.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="is_hidden",
            field=models.BooleanField(
                default=False,
                help_text="Source of truth for student visibility. True means students cannot access.",
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Auto-publish this draft at the given datetime.",
                null=True,
            ),
        ),
    ]
