# Generated by Django 5.2.7 on 2026-03-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homeworks", "0005_add_homework_expiry_and_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="homework_type",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("hidden", "Hidden"),
                ],
                default="published",
                help_text="Display label only. is_hidden is the access control source of truth.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Auto-publish this draft at the given datetime.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="is_hidden",
            field=models.BooleanField(
                default=False,
                help_text="Source of truth for student visibility. True means students cannot access.",
            ),
        ),
    ]
