# Generated by Codex on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks", "0006_add_draft_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="homework_type",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("published", "Published"),
                    ("hidden", "Hidden"),
                ],
                default="published",
                help_text="Display label only. is_hidden is the access control source of truth.",
                max_length=20,
            ),
        ),
    ]
