# Generated by Django 5.2.7 on 2026-03-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks", "0006_homework_homework_type_homework_publish_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="due_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Required before publishing. Drafts may leave this blank.",
                null=True,
            ),
        ),
    ]
