# Generated by Django 5.2.13 on 2026-05-03 20:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks", "0007_add_scheduled_homework_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeworkProgressWidget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pre_prompt",
                    models.TextField(
                        help_text="Prompt shown to student before starting homework"
                    ),
                ),
                (
                    "post_prompt",
                    models.TextField(
                        help_text="Prompt shown to student after completing homework"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Order of the widget (determines opening/closing order)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_widgets",
                        to="homeworks.homework",
                    ),
                ),
            ],
            options={
                "db_table": "homeworks_progress_widget",
                "ordering": ["order"],
                "unique_together": {("homework", "order")},
            },
        ),
    ]
